apiVersion: v1
kind: Secret
metadata:
  name: spring-boot-application-properties
type: Opaque
stringData:
  application.properties: |
    # Kafka
    spring.kafka.properties.sasl.mechanism=PLAIN
    spring.kafka.properties.bootstrap.servers=server
    spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule   required username='key'   password='password';
    spring.kafka.properties.security.protocol=SASL_SSL
    # Confluent Cloud Schema Registry
    spring.kafka.properties.basic.auth.credentials.source=USER_INFO
    spring.kafka.properties.schema.registry.basic.auth.user.info=sr_key:sr_password
    spring.kafka.properties.schema.registry.url=https://sr_url
    spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.LongSerializer
    spring.kafka.producer.value-serializer=io.confluent.kafka.serializers.KafkaAvroSerializer
    my.topics.replication.factor=3
    my.topics.partitions.count=6
  