apiVersion: v1
kind: Secret
metadata:
  name: spring-boot-ratings-processor-application-properties
type: Opaque
stringData:
  application.properties: |
    spring.kafka.streams.application-id=rating-processor
    # Kafka
    spring.kafka.properties.sasl.mechanism=PLAIN
    spring.kafka.properties.bootstrap.servers={server}
    spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule   required username='key'   password='password';
    spring.kafka.properties.security.protocol=SASL_SSL
    # Confluent Cloud Schema Registry
    spring.kafka.properties.basic.auth.credentials.source=USER_INFO
    spring.kafka.properties.schema.registry.basic.auth.user.info=key:password
    spring.kafka.properties.schema.registry.url=https://sr_url

    spring.kafka.streams.replication-factor=3
    # application specific
    my.topics.replication.factor=3
    my.topics.partitions.count=6
    my.topics.movies.name=movies
    my.topics.ratings.name=ratings
    my.topic.avg-ratings.name=average-ratings
    my.topic.rated-movies.name=rated-movies
