apiVersion: v1
kind: Secret
metadata:
  name: twitter-connector.json
type: Opaque
stringData:
  # get api keys and secrets at developer.twitter.com
  twitter-connector.json: '{
      "name": "twitter_source",
      "config": {
        "connector.class": "com.github.jcustenborder.kafka.connect.twitter.TwitterSourceConnector",
        "twitter.oauth.consumerKey": "KEY",
        "twitter.oauth.consumerSecret": "KEY_SECRET",
        "twitter.oauth.accessToken": "TOKEN",
        "twitter.oauth.accessTokenSecret": "TOKEN_SECRET",
        "value.converter": "org.apache.kafka.connect.json.JsonConverter",
        "key.converter": "org.apache.kafka.connect.json.JsonConverter",
        "value.converter.schemas.enable": false,
        "key.converter.schemas.enable": false,
        "kafka.status.topic": "twitter_json_01",
        "kafka.delete.topic": "twitter_json_01_deletes",
        "process.deletes": true,
        "filter.keywords": "gamussa",
        "tasks.max": "1"
      }
    }'
